### ISSUE TITLE
Changing Browser Language

### ISSUE THREAD

**Issue by itzRykon** [JetBrains/jcef#10]
Hey, 

i tried a few ways to change the Browser Language but its not changing. Thats a snipped out of my code:

        settings = new CefSettings();
        settings.windowless_rendering_enabled = useOSR;
        settings.locale = "de";
        //settings.locale = "de-DE";

        cefApp = CefApp.getInstance(settings);
        CefApp.getInstance(settings);
        client = cefApp.createClient();
        browser = client.createBrowser(startURL, useOSR, isTransparent);

i dont know what is wrong there , i hope there is some help :) , probably im only bit dump and it works easy :D

Thanks guys

**Comment by ujpv** [comment]
I see that it's a very old question. Probably the corresponding language has to installed to the OS.
I'm closing this issue. Feel free to file a [bug](https://youtrack.jetbrains.com/newIssue?project=JBR&description=**Problem+description**%0A%5BA+short+problem+description%5D%0A%0A**Way+to+reproduce**%0A1.+Open++%E2%80%A6%0A2.+Go+to+%E2%80%A6%0A3.+Press+or+click+%E2%80%A6%0A4.+Observer+%E2%80%A6%0A5.+Expected+%E2%80%A6%0A%0A**Screen+records+or+screenshorts**%0A%5BPut+here+some+video+or+pictures+if+applicable%5D%0A%0A**Version+and+environment**%0AJetBrains+Runtime+version%3A+%5Bexample+17.0.8%2B7-b1000.22+aarch64.+In+a+JetBrains+IDEs+it+can+be+copied+from+%60About+IntelliJ+IDEA%60%2C+%60About+Clion%60+etc.%5D+%0AOS%3A+%5Bput+here+the+OS+name+and+version%28e.g.+macOS+13.4.1+%2C+Ubuntu+22.10%2C+Windows+11%29%5D%0ACPU%3A+%5Bput+here+CPU+architecture+like+arm64%2C+M1%2C+M2%2C+x86%2C+etc.%5D%0AAdditional+info%3A+%5BAnything+you+think+might+be+important+in+your+environment.+For+example%2C+in+the+case+of+graphics+problems%2C+you+can+tell+us+the+number+of+monitors+you+are+using%2C+their+resolutions+and+scaling+factors%5D%0A%0A**Additional+context**%0A%5Bput+here%5D%0A%0A%0A%0A&c=add+Board+Bug2Fix+Vitaly+Provodin&c=add+Board+JBR+Planing+No+Fix+versions&c=Subsystem+jcef&c=Assignee+Vladimir.Kharitonov) if the problem takes place.
