### ISSUE TITLE
Access denied when downloading latest CEF binary

### ISSUE THREAD

**Issue by huyz-git** [JetBrains/jcef#11]
```
$ curl -L https://cache-redirector.jetbrains.com/intellij-jbr/cef_binary_98.3.42%2Bgf00e174%2Bchromium-98.0.4758.102_linux64_minimal.zip
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>7CMVXGS394HTMF8D</RequestId><HostId>lo+JHZpnK4e9fkzE7sgrw912M8lMT5kfeakVfRhI3Gpsezdfnxzqq9m2ZPA2zVoduWLZ/DsfICM=</HostId></Error>
```
The last version 98.3.34 ( https://cache-redirector.jetbrains.com/intellij-jbr/cef_binary_98.3.34%2Bg97a5ae6%2Bchromium-98.0.4758.102_linux64_minimal.zip. ) can download.

**Comment by ayanamist** [comment]
It seems they still use old one https://github.com/JetBrains/intellij-community/blob/master/.idea/libraries/jcef.xml

**Comment by liff** [comment]
Doubt it’ll help but: [JBR-5087](https://youtrack.jetbrains.com/issue/JBR-5087).

**Comment by ujpv** [comment]
It's a pretty link version. Please check the main branch. https://github.com/JetBrains/jcef/tree/dev

It should work
