### ISSUE TITLE
Google thinks JCEF is not safe

### ISSUE THREAD

**Issue by LiLittleCat** [JetBrains/jcef#14]
I have written a [plugin](https://github.com/LiLittleCat/intellij-chatgpt) through JCEF to render web pages where the web page can be logged in through a Google account. When logging in with my Google account it prompts that the current browser is not secure, how can I avoid this? Where can I get help with this? Any information you can provide would be greatly appreciated.

**Comment by mikehearn** [comment]
This is caused by their anti-bot protections, don't try to work around it, it's a lot  of effort. Better to delegate the login to the user's own browser using OAuth.

**Comment by avu** [comment]
@artemm-bochkarev could you please have a look

**Comment by ujpv** [comment]
Yes, Google thinks JCEF is not safe. We can't do much about this as well as we recommend to not workaround this. It's better to other ways for authentication.
