### ISSUE TITLE
When css sets cursor, the mouse pointer will blink

### ISSUE THREAD

**Issue by AlanCZ** [JetBrains/jcef#15]
When css sets cursor, the mouse pointer will blink

**Comment by songyanbo** [comment]
Is there a solution to this problem?

**Comment by ujpv** [comment]
I tried on MacOS. Don't see blinking.
May you pls, provide more details in a bug according to the [template](https://youtrack.jetbrains.com/newIssue?project=JBR&description=**Problem+description**%0A%5BA+short+problem+description%5D%0A%0A**Way+to+reproduce**%0A1.+Open++%E2%80%A6%0A2.+Go+to+%E2%80%A6%0A3.+Press+or+click+%E2%80%A6%0A4.+Observer+%E2%80%A6%0A5.+Expected+%E2%80%A6%0A%0A**Screen+records+or+screenshorts**%0A%5BPut+here+some+video+or+pictures+if+applicable%5D%0A%0A**Version+and+environment**%0AJetBrains+Runtime+version%3A+%5Bexample+17.0.8%2B7-b1000.22+aarch64.+In+a+JetBrains+IDEs+it+can+be+copied+from+%60About+IntelliJ+IDEA%60%2C+%60About+Clion%60+etc.%5D+%0AOS%3A+%5Bput+here+the+OS+name+and+version%28e.g.+macOS+13.4.1+%2C+Ubuntu+22.10%2C+Windows+11%29%5D%0ACPU%3A+%5Bput+here+CPU+architecture+like+arm64%2C+M1%2C+M2%2C+x86%2C+etc.%5D%0AAdditional+info%3A+%5BAnything+you+think+might+be+important+in+your+environment.+For+example%2C+in+the+case+of+graphics+problems%2C+you+can+tell+us+the+number+of+monitors+you+are+using%2C+their+resolutions+and+scaling+factors%5D%0A%0A**Additional+context**%0A%5Bput+here%5D%0A%0A%0A%0A&c=add+Board+Bug2Fix+Vitaly+Provodin&c=add+Board+JBR+Planing+No+Fix+versions&c=Subsystem+jcef&c=Assignee+Vladimir.Kharitonov). E.g. JBR version, OS, etc
An example of CSS is appreciated.

**Comment by Yuanuo** [comment]
I'm having the same issue and found that listening to onCursorChange fixes this flickering issue (Kotlin code):

```
        val client = ...
        client.addDisplayHandler(object: CefDisplayHandlerAdapter() {
            override fun onCursorChange(browser: CefBrowser?, cursorType: Int): Boolean {
                browser?.uiComponent?.cursor = java.awt.Cursor.getPredefinedCursor(cursorType);
                return false
            }
        })
        val browser = ...
```

**Comment by xzxiaoshan** [comment]
I also encountered a flashing issue, idea 2023、 Both 2024 and 2025 have the same problem.

windows11

**Comment by KlemenDEV** [comment]
This happens on Windows still, the workaround of @Yuanuo just makes this slightly less annoying but still present. Please reopen

Any change of cursor so CSS-specified cursor differs from the cursor set in Java will cause this.

Does not happen with OSR
