### ISSUE TITLE
Video Wake Lock on Linux Mint

### ISSUE THREAD

**Issue by starsep** [JetBrains/jcef#18]
I am using PyCharm Community with New UI enabled on Linux Mint.

While trying to suspend computer there is warning due to `Video Wake Lock` on `jcef`
![image](https://github.com/JetBrains/jcef/assets/2798728/61e1f4b7-54d9-424a-b262-04e3b5f660d6)
Is it possible to disable this lock?

PS I am not sure whether this is the correct place to report it.

**Comment by ujpv** [comment]
Hi @starsep ,
Thank you for the report!
May you pls file a bug at our [youtrack](https://youtrack.jetbrains.com/newIssue?project=JBR&description=**Problem+description**%0A%5BA+short+problem+description%5D%0A%0A**Way+to+reproduce**%0A1.+Open++%E2%80%A6%0A2.+Go+to+%E2%80%A6%0A3.+Press+or+click+%E2%80%A6%0A4.+Observer+%E2%80%A6%0A5.+Expected+%E2%80%A6%0A%0A**Screen+records+or+screenshorts**%0A%5BPut+here+some+video+or+pictures+if+applicable%5D%0A%0A**Version+and+environment**%0AJetBrains+Runtime+version%3A+%5Bexample+17.0.8%2B7-b1000.22+aarch64.+In+a+JetBrains+IDEs+it+can+be+copied+from+%60About+IntelliJ+IDEA%60%2C+%60About+Clion%60+etc.%5D+%0AOS%3A+%5Bput+here+the+OS+name+and+version%28e.g.+macOS+13.4.1+%2C+Ubuntu+22.10%2C+Windows+11%29%5D%0ACPU%3A+%5Bput+here+CPU+architecture+like+arm64%2C+M1%2C+M2%2C+x86%2C+etc.%5D%0AAdditional+info%3A+%5BAnything+you+think+might+be+important+in+your+environment.+For+example%2C+in+the+case+of+graphics+problems%2C+you+can+tell+us+the+number+of+monitors+you+are+using%2C+their+resolutions+and+scaling+factors%5D%0A%0A**Additional+context**%0A%5Bput+here%5D%0A%0A%0A%0A&c=add+Board+Bug2Fix+Vitaly+Provodin&c=add+Board+JBR+Planing+No+Fix+versions&c=Subsystem+jcef&c=Assignee+Vladimir.Kharitonov). 
We use it to track and plan work on JCEF. There also some fields in the template to be fill out that could help us to deal with the problem.

**Comment by starsep** [comment]
I haven't reported this issue to youtrack because I no longer can reproduce it.
I suspect either some OS or IDE update changed this behaviour
