### ISSUE TITLE
Markdown preview not work

### ISSUE THREAD

**Issue by ghost** [JetBrains/jcef#26]
The markdown file preview does not work with the built-in JCEF versions, with Java installed from official servers, nor by compiling JCEF following the instructions from this repository.

Perhaps this is not the right place to express certain opinions, but I believe this repository is frequented by JetBrains developers, and it is to them that I am addressing this.

There are hundreds and hundreds of posts online complaining about this issue, and in the official documentation on your website, there is even a note mentioning it, linking to an external site where there should be a solution. However, the solution is not for PhpStorm, but for Android Studio, which, while a derived product, is significantly customized by Google.

The automatic thought that comes to mind is this: I understand JetBrains' company policies aimed at continuous improvement, and I also understand that the percentage of dissatisfied users is truly small and likely negligible for you. However, I believe it would take little effort and time to restore a version of the markdown plugin from before the introduction of JCEF, to allow those who cannot get the preview to still have a user experience that, frankly, right now is quite poor.

Other than that, the product is truly excellent. It’s just a shame about this small detail.

Have a good evening

**Comment by ujpv** [comment]
Please file a ticket with clear and precise way to reproduce the problem.
https://youtrack.jetbrains.com/issues/JBR
JCEF is distributed as part of IJ platform based IDEs. It's a bit tricky to get working in IJ platform JCEF builds.
